name: Build Server and Client

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends \
            cmake \
            build-essential \
            qtbase5-dev \
            qtdeclarative5-dev \
            qml-module-qtquick2 \
            libqt5websockets5-dev \
            qtwebengine5-dev

      - name: Build Server
        run: |
          cd server
          mkdir -p build && cd build
          cmake .. -DCMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/cmake/Qt5
          cmake --build . --parallel $(nproc)

      - name: Build Client
        run: |
          cd ClientQml
          mkdir -p build && cd build
          cmake .. -DCMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/cmake/Qt5
          cmake --build . --parallel $(nproc)

      - name: Build Front-interface
        run: |
          cd front
          mkdir -p build && cd build
          cmake .. -DCMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/cmake/Qt5
          cmake --build . --parallel $(nproc)
