name: Build Qt/QML with CMake (Ubuntu)

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Qt and dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends \
            git \
            cmake \
            build-essential \
            qtbase5-dev \
            qtdeclarative5-dev \
            qtquickcontrols2-5-dev \
            qml-module-qtquick2 \
            qml-module-qtquick-controls2

      - name: Configure and Build
        run: |
          cd server
          mkdir -p build && cd build
          cmake .. -DCMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/cmake/Qt5
          cmake --build . --parallel $(nproc)
